class_names = [
    "Banh canh (Vietnamese thick noodle soup)",
    "Banh chung (Square sticky rice cake)",
    "Banh cuon (Rolled rice pancake)",
    "Banh khot (Mini savory pancakes)",
    "Banh mi (Vietnamese baguette sandwich)",
    "Banh trang (Rice paper)",
    "Banh trang tron (Rice paper salad)",
    "Banh xeo (Vietnamese sizzling pancake)",
    "Bo kho (Beef stew)",
    "Bo la lot (Grilled beef wrapped in betel leaves)",
    "Bong cai (Cauliflower)",
    "Bun (Rice vermicelli)",
    "Bun bo Hue (Hue beef noodle soup)",
    "Bun cha (Grilled pork with vermicelli)",
    "Bun dau (Vermicelli with tofu)",
    "Bun mam (Fermented fish noodle soup)",
    "Bun rieu (Crab noodle soup)",
    "Ca (Fish)",
    "Ca chua (Tomato)",
    "Ca phao (Pickled eggplant)",
    "Ca rot (Carrot)",
    "Canh (Soup)",
    "Cha (Vietnamese pork roll)",
    "Cha gio (Spring rolls)",
    "Chanh (Lime)",
    "Com (Rice)",
    "Com tam (Broken rice)",
    "Con nguoi (Human)",
    "Cu kieu (Pickled scallion head)",
    "Cua (Crab)",
    "Dau hu (Tofu)",
    "Dua chua (Pickled vegetables)",
    "Dua leo (Cucumber)",
    "Goi cuon (Fresh spring rolls)",
    "Hamburger",
    "Heo quay (Roast pork)",
    "Hu tieu (Clear rice noodle soup)",
    "Kho qua thit (Stuffed bitter melon soup)",
    "Khoai tay chien (French fries)",
    "Lau (Hotpot)",
    "Long heo (Pork offal)",
    "Mi (Egg noodles)",
    "Muc (Squid)",
    "Nam (Mushroom)",
    "Oc (Snails)",
    "Ot chuong (Bell pepper)",
    "Pho (Vietnamese noodle soup)",
    "Pho mai (Cheese)",
    "Rau (Vegetables)",
    "Salad (Salad)",
    "Thit bo (Beef)",
    "Thit ga (Chicken)",
    "Thit heo (Pork)",
    "Thit kho (Braised pork)",
    "Thit nuong (Grilled meat)",
    "Tom (Shrimp)",
    "Trung (Egg)",
    "Xoi (Sticky rice)",
]
