class_names = [
    "Bánh canh (Vietnamese thick noodle soup)",
    "Bánh chưng (Square sticky rice cake)",
    "Bánh cuốn (Rolled rice pancake)",
    "Bánh khọt (Mini savory pancakes)",
    "Bánh mì (Vietnamese baguette sandwich)",
    "Bánh tráng (Rice paper)",
    "Bánh tráng trộn (Rice paper salad)",
    "Bánh xèo (Vietnamese sizzling pancake)",
    "Bò kho (Beef stew)",
    "Bò lá lốt (Grilled beef wrapped in betel leaves)",
    "Bông cải (Cauliflower)",
    "Bún (Rice vermicelli)",
    "Bún bò Huế (Hue beef noodle soup)",
    "Bún chả (Grilled pork with vermicelli)",
    "Bún đậu (Vermicelli with tofu)",
    "Bún mắm (Fermented fish noodle soup)",
    "Bún riêu (Crab noodle soup)",
    "Cá (Fish)",
    "Cà chua (Tomato)",
    "Cà pháo (Pickled eggplant)",
    "Cà rốt (Carrot)",
    "Canh (Soup)",
    "Chả (Vietnamese pork roll)",
    "Chả giò (Spring rolls)",
    "Chanh (Lime)",
    "Cơm (Rice)",
    "Cơm tấm (Broken rice)",
    "Con người (Human)",
    "Củ kiệu (Pickled scallion head)",
    "Cua (Crab)",
    "Đậu hũ (Tofu)",
    "Dưa chua (Pickled vegetables)",
    "Dưa leo (Cucumber)",
    "Gỏi cuốn (Fresh spring rolls)",
    "Hamburger",
    "Heo quay (Roast pork)",
    "Hủ tiếu (Clear rice noodle soup)",
    "Khổ qua thịt (Stuffed bitter melon soup)",
    "Khoai tây chiên (French fries)",
    "Lẩu (Hotpot)",
    "Lòng heo (Pork offal)",
    "Mì (Egg noodles)",
    "Mực (Squid)",
    "Nấm (Mushroom)",
    "Ốc (Snails)",
    "Ớt chuông (Bell pepper)",
    "Phở (Vietnamese noodle soup)",
    "Phô mai (Cheese)",
    "Rau (Vegetables)",
    "Salad (Salad)",
    "Thịt bò (Beef)",
    "Thịt gà (Chicken)",
    "Thịt heo (Pork)",
    "Thịt kho (Braised pork)",
    "Thịt nướng (Grilled meat)",
    "Tôm (Shrimp)",
    "Trứng (Egg)",
    "Xôi (Sticky rice)"
]
