class_names = [
    "Banh_canh (Vietnamese thick noodle soup)",
    "Banh_chung (Square sticky rice cake)",
    "Banh_cuon (Rolled rice pancake)",
    "Banh_khot (Mini savory pancakes)",
    "Banh_mi (Vietnamese baguette sandwich)",
    "Banh_trang (Rice paper)",
    "Banh_trang_tron (Rice paper salad)",
    "Banh_xeo (Vietnamese sizzling pancake)",
    "Bo_kho (Beef stew)",
    "Bo_la_lot (Grilled beef wrapped in betel leaves)",
    "Bong_cai (Cauliflower)",
    "Bun (Rice vermicelli)",
    "Bun_bo_Hue (Hue beef noodle soup)",
    "Bun_cha (Grilled pork with vermicelli)",
    "Bun_dau (Vermicelli with tofu)",
    "Bun_mam (Fermented fish noodle soup)",
    "Bun_rieu (Crab noodle soup)",
    "Ca (Fish)",
    "Ca_chua (Tomato)",
    "Ca_phao (Pickled eggplant)",
    "Ca_rot (Carrot)",
    "Canh (Soup)",
    "Cha (Vietnamese pork roll)",
    "Cha_gio (Spring rolls)",
    "Chanh (Lime)",
    "Com (Rice)",
    "Com_tam (Broken rice)",
    "Con_nguoi (Human)",
    "Cu_kieu (Pickled scallion head)",
    "Cua (Crab)",
    "Dau_hu (Tofu)",
    "Dua_chua (Pickled vegetables)",
    "Dua_leo (Cucumber)",
    "Goi_cuon (Fresh spring rolls)",
    "Hamburger",
    "Heo_quay (Roast pork)",
    "Hu_tieu (Clear rice noodle soup)",
    "Kho_qua_thit (Stuffed bitter melon soup)",
    "Khoai_tay_chien (French fries)",
    "Lau (Hotpot)",
    "Long_heo (Pork offal)",
    "Mi (Egg noodles)",
    "Muc (Squid)",
    "Nam (Mushroom)",
    "Oc (Snails)",
    "Ot_chuong (Bell pepper)",
    "Pho (Vietnamese noodle soup)",
    "Pho_mai (Cheese)",
    "Rau (Vegetables)",
    "Salad (Salad)",
    "Thit_bo (Beef)",
    "Thit_ga (Chicken)",
    "Thit_heo (Pork)",
    "Thit_kho (Braised pork)",
    "Thit_nuong (Grilled meat)",
    "Tom (Shrimp)",
    "Trung (Egg)",
    "Xoi (Sticky rice)",
]